// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go.opentelemetry.io/otel/sdk/trace"
	"kratos_sim/app/user/service/internal/biz"
	"kratos_sim/app/user/service/internal/conf"
	data2 "kratos_sim/app/user/service/internal/data"
	"kratos_sim/app/user/service/internal/server"
	"kratos_sim/app/user/service/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, registry *conf.Registry, logger log.Logger, tp *trace.TracerProvider) (*kratos.App, func(), error) {
	gormDB := data2.NewDB(confData, logger)
	dataData, cleanup, err := data2.NewData(gormDB, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data2.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userService := service.NewUserService(userUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, auth, tp, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
